### ISSUE TITLE
DNS for connectivity test site not available during authentication

### ISSUE THREAD

**Issue by NKID00** [ArcticLampyrid/njupt_wifi_login#1]
The connectivity test site cannot be reached during authentication in case of dns cache miss.

```
Failed to connect: http request failed: error sending request for url (http://connect.rom.miui.com/generate_204): error trying to connect: dns error: 不知道这样的主机。 (os error 11001)
```

Using a predefined ip address to test connectivity (or backing up with it) will solve this.

**Comment by ArcticLampyrid** [comment]
I’m curious whether DNS is available before logining the AP. It seems that auto-redirect may not work if not available. But most users rely on auto-redirect to open the login page.

**Comment by NKID00** [comment]
There is a dns server `10.10.240.8` that is reachable during authentication, but somehow it is left unused.

**Comment by ArcticLampyrid** [comment]
Things get interested.
The gateway seems to allow some common DNS server like `8.8.8.8` passing by. But for servers not in the whitelist, the request will be blocked.
```
nslookup connect.rom.miui.com 10.22.240.8 //ok
nslookup connect.rom.miui.com 8.8.8.8 //ok
nslookup connect.rom.miui.com 119.29.29.29 //failed
```

**Comment by ArcticLampyrid** [comment]
Note that the host `p.njupt.edu.cn` may also be affected.

**Comment by ArcticLampyrid** [comment]
Fixed.
In v0.1.3 and afterwards, it will use Google DNS Servers (in the white list of the firewall) internally to avoid dns not available during authentication.
