### ISSUE TITLE
Won't log in automatically if njupt network is already connected before startup

### ISSUE THREAD

**Issue by invinciblesmalltree** [ArcticLampyrid/njupt_wifi_login#5]
When starting up, the boot process is very slow, and if the njupt network is already connected before startup, it won't log in automatically. It is recommended to check and log in during startup.

**Comment by ArcticLampyrid** [comment]
Actually we are checking it during startup.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: invinciblesmalltree ***@***.***>
发送时间: Tuesday, September 26, 2023 10:20:11 AM
收件人: ArcticLampyrid/njupt_wifi_login ***@***.***>
抄送: Subscribed ***@***.***>
主题: [ArcticLampyrid/njupt_wifi_login] Some bugs that have made my experience unpleasant (Issue #5)


When starting up, the boot process is very slow, and if the njupt network is already connected before startup, it won't log in automatically. It is recommended to check and log in during startup.

―

**Comment by ArcticLampyrid** [comment]
> When starting up, the boot process is very slow

You can now configure this tool to run as a Windows service, ensuring it starts at the very beginning.
